version: "3.9"
services:
  mysql:
    container_name: teste-globo-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: teste-globo
      MYSQL_USER: teste-globo
      MYSQL_PASSWORD: teste-globo
      MYSQL_ROOT_PASSWORD: teste-globo
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
